[[language]]
name = "html"
file-types = [ "hbs" ]
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "css"
file-types = [ "less" ]
formatter = { command = 'prettier', args = ["--parser", "css"] }
