# Adapted from dnd5e & Draw-Steel
name: Release Creation

env:
  NODE_VERSION: 22

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Get part of the tag after the `v`.
      - name: Extract tag version number
        id: get_version
        uses: battila7/get-version-action@v2

      # Modify manifest version, download, esmodules, styles, remove hotreload.
      - name: Modify Manifest to remove HotReload
        uses: microsoft/variable-substitution@v1
        with:
          files: "metallurgent0th/system.json"
        env:
          flags.hotReload: false
          version: ${{steps.get_version.outputs.version-without-v}}
          download: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/metallurgent0th.zip

      # Set up Node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      # `npm ci` is recommended:
      # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
      - name: Install Dependencies
        run: npm ci

      # Run build script
      - name: Build All
        run: |
          npm run prepareRelease
          mv --force LICENSE metallurgent0th/LICENSE

      # Create zip file.
      - name: Create ZIP archive
        run: zip -r ./metallurgent0th.zip metallurgent0th

			# Create a release for this specific version.
      - name: Update Release with Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          omitNameDuringUpdate: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./metallurgent0th/system.json, ./metallurgent0th.zip"
          tag: ${{ github.event.release.tag_name }}
          makeLatest: false
          prerelease: true
          body: |
            ${{ github.event.release.body }}

            **Installation:** To manually install this release, please use the following manifest URL: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/system.json
